// SERVANTS
export const GET_SERVANTS_NICE = "GET_SERVANTS_NICE";
export const GET_SERVANTS_BASIC = "GET_SERVANTS_BASIC";
export const GET_SERVANT = "GET_SERVANT";
export const GET_SERVANT_RANDOM = "GET_SERVANT_RANDOM";
export const GET_SERVANTS_BASIC_NA = "GET_SERVANTS_BASIC_NA";

// CEs
export const GET_CEs_NICE = "GET_CEs_NICE";
export const GET_CEs_BASIC = "GET_CEs_BASIC";
export const GET_CE = "GET_CE";

